### ISSUE TITLE
Custom organization logo?

### ISSUE THREAD

**Issue by ararslan** [JuliaData/Roadmap.jl#2]
It might be nice to have a custom logo for this organization. So... call for proposals!

**Comment by cormullion** [comment]
While looking for org logos... I couldn't resist whipping up a few ideas (although the subject matter wasn't particularly easy :)). Here are 200x200 versions:

1: 
![julia-data-2-200](https://cloud.githubusercontent.com/assets/52289/23015959/af084aa4-f42c-11e6-9b3d-d4047cb2b409.png)

2: 

![julia-data-3-200](https://cloud.githubusercontent.com/assets/52289/23015961/af2344a8-f42c-11e6-8c42-29c238827031.png)

3:

![julia-data-200](https://cloud.githubusercontent.com/assets/52289/23015962/af25ac98-f42c-11e6-9b52-5ac3119557a9.png)

Here are the 500 by 500 versions:

![julia-data-2](https://cloud.githubusercontent.com/assets/52289/23016057/174096a8-f42d-11e6-9f42-c36e59b17210.png)
![julia-data-3](https://cloud.githubusercontent.com/assets/52289/23016059/1a9da458-f42d-11e6-9014-28b5ee258c4a.png)
![julia-data](https://cloud.githubusercontent.com/assets/52289/23016062/1ed33f56-f42d-11e6-8d9a-c6e6cc35dc6d.png)

**Comment by nalimilan** [comment]
Thanks for working on this. I would say the idea of your proposal 2 is the most explicit one: indeed what this organization is about is working with tabular data, so showing a table sounds like the way to go. Though maybe the colors should be more similar within a column and more different between, so that the cells do not appear to be completely isolated? This is what differentiates a data table from an array. The first column (with dots for row IDs) could also be made more distinct from the header, to reflect how a data table is typically printed.

I also wonder whether we should show three tables (which mirrors the Julia logo) or a single one. Maybe the three dots of the Julia logo could appear inside the table, like the JuliaPackaging logo? Then the table cells could be in grey, with one shade for each column).

Anyway, these are the suggestions I can make.

**Comment by cormullion** [comment]
Good stuff - I like your thinking! I'll whip up a few more versions this week and see what emerges...

**Comment by cormullion** [comment]
So here are six ideas, three from earlier and three more:

![tiled-images](https://cloud.githubusercontent.com/assets/52289/23501316/586bae7a-ff2b-11e6-8271-378a3b27bb99.png)

For a makeshift GitHub poll you could use the six reaction emojis to "vote" for the numbers of the ideas (although you can't then register -1 and Confused feelings... :))

![voting-icons](https://cloud.githubusercontent.com/assets/52289/23501408/a46b1bbc-ff2b-11e6-96d2-73186177653e.png)

**Comment by nalimilan** [comment]
Maybe a variant of no. 2 but with the per-column colors of no. 4? Could also try with the columns being a bit larger, as in typical tables cells are rectangular, not square.

**Comment by cormullion** [comment]
Sure thing...!

![julia-data-7-200](https://cloud.githubusercontent.com/assets/52289/23552112/248c2444-0012-11e7-98c6-44540bcc95af.png)

(Although, since this is a logo not a diagram it's possible (IMO) to start overthinking its design... :))

**Comment by nalimilan** [comment]
Thanks. That's not bad, but I'm not sure which one I prefer. The new one is a bit blurry, which might not do it justice.

That's just for the fun of bikeshedding, but have you tried using one color for each table to mirror the Julia logo? The columns inside each table could use different shades to make them distinct (maybe even with just two shades).

**Comment by cormullion** [comment]
Yes, it's not too bad:

![julia-data-7-200](https://cloud.githubusercontent.com/assets/52289/23555566/53d6d1d6-0021-11e7-9162-c9d6d7aaa4e4.png)

**Comment by ararslan** [comment]
I think my favorite is still #&#8203;2 above, though I do like this most recent one as well. Seems above we have a tie between #&#8203;2 and #&#8203;3.

**Comment by cormullion** [comment]
@ararslan need more voters :)

**Comment by cjprybol** [comment]
The only thing I find confusing about 2 is that the column headers and the leftmost column (presumably the row index column?) have the same symbols (gray circle). I like how in the most recent 2 examples there is a clearer distinction between the visual cues in the row index column and the column headers, which captures how users will interact with row indices (numerical/boolean indexing) and column indices (numerical/boolean/symbol indexing) differently. If the leftmost row-index column is removed or updated to look more like the most recent 2 examples then I would be happy to swap my vote from 3 -> 2! Thanks for producing all of these examples @cormullion!

**Comment by cormullion** [comment]
@cjprybol Good ideas. It's a fun if unimportant problem space, and it does a bit of testing of my Julia package Luxor on the way. I think the only decent one is number 3, the others are just diagrams posing as icons... :)

**Comment by ViralBShah** [comment]
I like the number 3 logo the best.

**Comment by nalimilan** [comment]
Number 3 looks good, but it's hard to see the relationship with tabular data. Maybe it could be slightly modified so that the first row (and column?) would look different from the others?

**Comment by cormullion** [comment]
![juliadata](https://cloud.githubusercontent.com/assets/52289/24093842/cc60ff26-0d4d-11e7-9e7a-c5ccce564e86.png)

**Comment by nalimilan** [comment]
Thanks, the last logo is quite good too. I'm not sure which one I prefer now (compared with the one just above). Let's see what the poll says.

**Comment by ViralBShah** [comment]
Don't poll. Go with the last one. :-)

**Comment by ararslan** [comment]
There seems to be significant consensus toward the most recent one at 9 ❤️s as of this writing (only 8 hours after it was posted!), including from JuliaData members. Thus I've set that as the organization logo. If anyone objects we can always change it, but in the meantime I think this is certainly better than nothing at all. 😉

Really though, if anyone objects to the new logo, please don't hesitate to say so. But until then, I think this issue has served its purpose, and as such I will close it.

Thank you everyone for your feedback, and a *huge* thanks to @cormullion for taking the time to make these and helping JuliaData find its visual identity. You certainly have an eye for design, and you yourself deserve 9 ❤️s for your efforts.

**Comment by nalimilan** [comment]
Thanks @cormullion!

We'll have to update the CategoricalArrays manual, which uses an older version of this logo.

**Comment by cormullion** [comment]
Thanks @ararslan, @nalimilan for the feedback! It was fun, almost as much as working on the documentation! :)
