### ISSUE TITLE
Please add support for fst!

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/Roadmap.jl#4]
There's some rreally cool stuff happening with fst (http://fstpackage.org/). Please do add fst.jl to the list of supported packages!

**Comment by ararslan** [comment]
Indeed fst looks neat, but I'm not sure anyone in this organization currently has the bandwidth to either:

1. Translate the fst code base to Julia. The license is BSD-2 so licensing would work out okay, but the code base is quite large, continually evolving, and contains both R and C++.

2. Develop bindings to fst from Julia using either [RCall](https://github.com/JuliaInterop/RCall.jl) or [Cxx](https://github.com/Keno/Cxx.jl).

I encourage anyone interested in fst integration for Julia to try their hand at developing the package. I think it's quite unlikely that it will happen in the JuliaData organization anytime soon, if at all.

**Comment by nalimilan** [comment]
Yeah, I'm not sure it's worth keeping an issue open for this. If somebody wants to implement this, that would be nice, but we're not a centralized organization which decides who works on what. (Also we have much more serious problems right now than implementing something faster than Feather.)

**Comment by ararslan** [comment]
> we're not a centralized organization which decides who works on what

Except we can declare that we _won't_ work on this. 😄

**Comment by xiaodaigh** [comment]
https://github.com/xiaodaigh/fstformat.jl

I put my own naive RCall based implementation up

**Comment by ararslan** [comment]
Cool!
